# Site
repository: SPICYJO/spicyjo.github.io
favicon: images/favicon.ico

# Personal info
name: Seungwoo Jo
title: Undergraduate Student
email: sjosjo1204@gmail.com
website: spicyjo.github.io

# Social links
# twitter_username: facespics
github_username:  SPICYJO
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
youtube_username: channel/UCsfJIT6fbpew1fiwiKiZnsA
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am Seungwoo Jo and about to graduate from Seoul National University, South Korea in February 2021. I currently major in computer science and mechanical engineering. I want to pursue my career in computer science.

  My current interests are:
  - Human Behavior and Context Sensing
  - Application of Research in Business

# I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Skills Section
# skill_title: Skills
skill_content: | # this will include new lines to allow paragraphs
  ####Programming Languages
  - C
  - JAVA
  - Python
  
  <small>Above languages are my most experienced ones. I like learning new languages such as OCaml. I am currently starting on learning Rust.</small>

  ####Tools
  - LaTeX

  ####Languages
   - Korean (Native)
   - English (Fluent)
   - Japanese (Intermediate)

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#    - Rock climbing
#    - Gaming
#    - Knitting
#    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)


# Footer
footer_show_references: true

# Build settings
remote_theme: SPICYJO/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
